### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by Sedighe-Raeisi**
I fixed the issue #5  and #3
I put a condition on excluding the division by zero.

### CODE REVIEW

**Comment by anishhs001** [comment]
Adding another line to mention the error in assigning 0 to b might be helpful

**Review by Sedighe-Raeisi — COMMENTED** [review]
I revewed it

**Comment by anishhs001** [comment]
Could you maybe add the print under the else condition?

**Review by anishhs001 — CHANGES_REQUESTED** [review]
Could you maybe add the print under the else condition?

**Comment by maedeh-amini** [comment]
Reviewed

**Review by anishhs001 — APPROVED** [review]
Looks good

**Review by maedeh-amini — DISMISSED** [review]
It is reviewed and the changes are positively applied.

**Review by anishhs001 — APPROVED** [review]
Looks good

**Pull request merged**
